name: Destroy All
on:
  push:
    branches:
      - main


permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::447356678585:role/github-actions-demo
          aws-region: us-east-2

      - name: Destroy ASG
        working-directory: asg
        run: terraform init && terraform destroy --auto-approve

      # - name: Destroy DB
      #   working-directory: db
      #   run: terraform init && terraform destroy --auto-approve

      - name: Destroy VPC
        working-directory: vpc
        run: terraform init && terraform destroy --auto-approve