name: VPC Deploy

permissions:
  id-token: write
  contents: read

# If someone pushes to main branch, then continue executing.
on:
  push:
    paths:
      - 'vpc/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.5


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::447356678585:role/github-actions-demo
          aws-region: us-east-2




      # Runs a single commaind using the runners shell.
      - name: Init
        working-directory: vpc
        run: |
          terraform init


      # Runs a single commaind using the runners shell.
      - name: Plan
        working-directory: vpc
        run: |
          terraform plan


      # Runs a single commaind using the runners shell.
      - name: Apply
        working-directory: vpc
        run: |
          terraform apply --auto-approve

